import type { Metadata } from 'next'
import './_style/globals.css'
import Header from './_components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
